In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('train.csv')

In [3]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [4]:
# total_rows = len(df)

# # Drop the last 10,000 rows if the total rows are greater than 10,000
# if total_rows > 1000:
#     df = df.iloc[:-1000]

# # If you want to reset the index after dropping rows
# df.reset_index(drop=True, inplace=True)

In [5]:
df=df.dropna()

In [6]:
df= df[['title','author','label']]

In [7]:
df['custom_column']= df['title']+df['author']

In [8]:
df

title  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...   
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2                      Why the Truth Might Get You Fired   
3      15 Civilians Killed In Single US Airstrike Hav...   
4      Iranian woman jailed for fictional unpublished...   
...                                                  ...   
20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799                          What Keeps the F-35 Alive   

                                          author  label  \
0                                  Darrell Lucus      1   
1                                Daniel J. Flynn      0   
2                             Consortiumnews.com      1   
3                                Jessica Purkiss      1   
4                                 Howard Portnoy      1   
...                                          ...    ...   
20795                              Jerome Hudson      0   
20796                           Benjamin Hoffman      0   
20797  Michael J. de la Merced and Rachel Abrams      0   
20798                                Alex Ansary      1   
20799                              David Swanson      1   

                                           custom_column  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2      Why the Truth Might Get You FiredConsortiumnew...  
3      15 Civilians Killed In Single US Airstrike Hav...  
4      Iranian woman jailed for fictional unpublished...  
...                                                  ...  
20795  Rapper T.I.: Trump a ’Poster Child For White S...  
20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...  
20797  Macy’s Is Said to Receive Takeover Approach by...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799             What Keeps the F-35 AliveDavid Swanson  

[18285 rows x 4 columns]

In [9]:
new_df= df[['custom_column','label']]

In [10]:
new_df

custom_column  label
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...      0
2      Why the Truth Might Get You FiredConsortiumnew...      1
3      15 Civilians Killed In Single US Airstrike Hav...      1
4      Iranian woman jailed for fictional unpublished...      1
...                                                  ...    ...
20795  Rapper T.I.: Trump a ’Poster Child For White S...      0
20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...      0
20797  Macy’s Is Said to Receive Takeover Approach by...      0
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1
20799             What Keeps the F-35 AliveDavid Swanson      1

[18285 rows x 2 columns]

In [11]:
new_df['custom_column']=new_df['custom_column'].str.lower()

C:\Users\Yuvraj\AppData\Local\Temp\ipykernel_3808\3579232291.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['custom_column']=new_df['custom_column'].str.lower()


In [12]:
new_df['custom_column']

0        house dem aide: we didn’t even see comey’s let...
1        flynn: hillary clinton, big woman on campus - ...
2        why the truth might get you firedconsortiumnew...
3        15 civilians killed in single us airstrike hav...
4        iranian woman jailed for fictional unpublished...
                               ...                        
20795    rapper t.i.: trump a ’poster child for white s...
20796    n.f.l. playoffs: schedule, matchups and odds -...
20797    macy’s is said to receive takeover approach by...
20798    nato, russia to hold parallel exercises in bal...
20799               what keeps the f-35 alivedavid swanson
Name: custom_column, Length: 18285, dtype: object

removing punctuation

In [13]:
import string

In [14]:
def remove_punc(input_string):
    translator= str.maketrans('','',string.punctuation)
    result_string=input_string.translate(translator)
    return result_string

In [15]:
new_df['custom_column']=new_df['custom_column'].apply(remove_punc)

C:\Users\Yuvraj\AppData\Local\Temp\ipykernel_3808\744046485.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['custom_column']=new_df['custom_column'].apply(remove_punc)


In [16]:
new_df['custom_column'][0]

'house dem aide we didn’t even see comey’s letter until jason chaffetz tweeted itdarrell lucus'

removing stopwords

In [17]:
from nltk.corpus import stopwords
removing_stopwords=stopwords.words('english')

In [18]:
stop_words = set(stopwords.words('english'))

In [19]:
def remove_stopwords(text):
    # Split the text into words
    words = text.split()
    
    # Filter out stopwords using list comprehension
    filtered_words = [word for word in words if word.lower() not in stop_words]
    
    # Join the filtered words into a string
    filtered_text = ' '.join(filtered_words)
    
    return filtered_text

In [20]:
new_df['custom_column']=new_df['custom_column'].apply(remove_stopwords)

C:\Users\Yuvraj\AppData\Local\Temp\ipykernel_3808\929521906.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['custom_column']=new_df['custom_column'].apply(remove_stopwords)


In [21]:
new_df

custom_column  label
0      house dem aide didn’t even see comey’s letter ...      1
1      flynn hillary clinton big woman campus breitba...      0
2                 truth might get firedconsortiumnewscom      1
3      15 civilians killed single us airstrike identi...      1
4      iranian woman jailed fictional unpublished sto...      1
...                                                  ...    ...
20795  rapper ti trump ’poster child white supremacy’...      0
20796  nfl playoffs schedule matchups odds new york t...      0
20797  macy’s said receive takeover approach hudson’s...      0
20798  nato russia hold parallel exercises balkansale...      1
20799                       keeps f35 alivedavid swanson      1

[18285 rows x 2 columns]

stemming 

In [22]:
import nltk
from nltk.stem.porter import PorterStemmer

In [23]:
ps=PorterStemmer()

In [24]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
        
    return ' '.join(y)

In [25]:
new_df['custom_column']=new_df['custom_column'].apply(stem)

C:\Users\Yuvraj\AppData\Local\Temp\ipykernel_3808\1008510291.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['custom_column']=new_df['custom_column'].apply(stem)


In [26]:
new_df

custom_column  label
0      hous dem aid didn’t even see comey’ letter jas...      1
1      flynn hillari clinton big woman campu breitbar...      0
2                 truth might get firedconsortiumnewscom      1
3      15 civilian kill singl us airstrik identifiedj...      1
4      iranian woman jail fiction unpublish stori wom...      1
...                                                  ...    ...
20795  rapper ti trump ’poster child white supremacy’...      0
20796  nfl playoff schedul matchup odd new york times...      0
20797  macy’ said receiv takeov approach hudson’ bay ...      0
20798  nato russia hold parallel exercis balkansalex ...      1
20799                        keep f35 alivedavid swanson      1

[18285 rows x 2 columns]

In [27]:
X= df['custom_column'].values
Y= df['label'].values

In [28]:
X

array(['House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted ItDarrell Lucus',
       'FLYNN: Hillary Clinton, Big Woman on Campus - BreitbartDaniel J. Flynn',
       'Why the Truth Might Get You FiredConsortiumnews.com', ...,
       'Macy’s Is Said to Receive Takeover Approach by Hudson’s Bay - The New York TimesMichael J. de la Merced and Rachel Abrams',
       'NATO, Russia To Hold Parallel Exercises In BalkansAlex Ansary',
       'What Keeps the F-35 AliveDavid Swanson'], dtype=object)

In [29]:
Y

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

vectorization(tf-idf)

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()

In [31]:
tf.fit(X)
X= tf.transform(X).toarray()

In [32]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
Y

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

In [34]:
X[0].shape

(29221,)

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)


In [36]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((14628, 29221), (3657, 29221), (14628,), (3657,))

In [37]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
from sklearn.linear_model import LogisticRegression
classfier=LogisticRegression()
classfier.fit(X_train,y_train)


LogisticRegression()

In [39]:
pred=classfier.predict(X_test)

In [40]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred))

0.9644517363959529
